/* letter-clips.js — GENERATED by tools/make-letter-audio.py. Do not edit.
   Which letter sounds ship as audio, and where each came from: an IPA
   symbol in slashes means the sound was synthesised from the symbol on
   the card, a word means it was cut out of that word.
   The clips are audio/letters/<key>.mp3, with a slower take of the same
   sound at <key>-slow.mp3 for the first, teaching reading.
   Voice: en_GB-cori-medium (Piper), trained on public-domain LibriVox recordings. */
window.LETTER_CLIPS = {
  'a': { from: 'cat', ms: 420, slowMs: 525 },
  'b': { from: '/b/', ms: 210, slowMs: 399 },
  'c': { from: '/k/', ms: 339, slowMs: 239 },
  'ch': { from: 'chip', ms: 299, slowMs: 489 },
  'ck': { from: '/k/', ms: 399, slowMs: 629 },
  'd': { from: '/d/', ms: 170, slowMs: 419 },
  'e': { from: 'egg', ms: 355, slowMs: 409 },
  'f': { from: 'safe', ms: 279, slowMs: 444 },
  'g': { from: '/ɡ/', ms: 379, slowMs: 419 },
  'h': { from: 'hat', ms: 164, slowMs: 259 },
  'i': { from: 'pig', ms: 329, slowMs: 525 },
  'j': { from: 'jam', ms: 319, slowMs: 559 },
  'k': { from: '/k/', ms: 399, slowMs: 489 },
  'l': { from: 'leaf', ms: 299, slowMs: 371 },
  'm': { from: 'mat', ms: 275, slowMs: 355 },
  'n': { from: 'nut', ms: 279, slowMs: 359 },
  'ng': { from: 'song', ms: 275, slowMs: 371 },
  'o': { from: 'dog', ms: 420, slowMs: 525 },
  'p': { from: '/p/', ms: 229, slowMs: 369 },
  'q': { from: 'queen', ms: 190, slowMs: 239 },
  'r': { from: 'rat', ms: 339, slowMs: 359 },
  's': { from: '/s/', ms: 307, slowMs: 498 },
  'sh': { from: 'ship', ms: 323, slowMs: 498 },
  't': { from: '/t/', ms: 239, slowMs: 299 },
  'th': { from: 'thin', ms: 275, slowMs: 355 },
  'u': { from: 'cup', ms: 349, slowMs: 525 },
  'v': { from: 'van', ms: 300, slowMs: 363 },
  'w': { from: 'web', ms: 275, slowMs: 339 },
  'wh': { from: 'web', ms: 227, slowMs: 339 },
  'x': { from: 'box', ms: 307, slowMs: 379 },
  'y': { from: '/j/', ms: 323, slowMs: 307 },
  'z': { from: 'lazy', ms: 196, slowMs: 339 },
};
