/* letter-clips.js — GENERATED by tools/make-letter-audio.py. Do not edit.
   Which letter sounds ship as audio, and where each came from: an IPA
   symbol in slashes means the sound was synthesised from the symbol on
   the card, a word means it was cut out of that word.
   The clips are audio/letters/<key>.mp3, with a slower take of the same
   sound at <key>-slow.mp3 for the first, teaching reading.
   rec: true means a recording of a person saying that sound on its own
   (audio-src/letters/, Sound City Reading, Kathryn Davis). The rest are
   synthesised: en_GB-cori-medium (Piper), trained on public-domain LibriVox recordings.
   `ipa` is the sound the clip claims to be, and tools/build.mjs refuses
   to build if it disagrees with what the card prints. */
window.LETTER_CLIPS = {
  'a': { from: '/æ/', ipa: '/æ/', ms: 479, slowMs: 479, rec: true },
  'ai': { from: 'rain', ipa: '/eɪ/', ms: 200, slowMs: 409 },
  'air': { from: 'chair', ipa: '/eə/', ms: 229, slowMs: 409 },
  'ar': { from: 'star', ipa: '/ɑː/', ms: 420, slowMs: 525 },
  'b': { from: '/b/', ipa: '/b/', ms: 249, slowMs: 328, rec: true },
  'c': { from: '/k/', ipa: '/k/', ms: 160, slowMs: 208, rec: true },
  'ch': { from: '/tʃ/', ipa: '/tʃ/', ms: 379, slowMs: 504 },
  'ck': { from: '/k/', ipa: '/k/', ms: 170, slowMs: 219, rec: true },
  'd': { from: '/d/', ipa: '/d/', ms: 249, slowMs: 329, rec: true },
  'e': { from: '/e/', ipa: '/e/', ms: 439, slowMs: 584, rec: true },
  'ear': { from: 'year', ipa: '/ɪə/', ms: 229, slowMs: 309 },
  'ee': { from: 'tree', ipa: '/iː/', ms: 307, slowMs: 525 },
  'er': { from: 'shirt', ipa: '/ɜː/', ms: 369, slowMs: 429 },
  'f': { from: '/f/', ipa: '/f/', ms: 339, slowMs: 339, rec: true },
  'g': { from: '/ɡ/', ipa: '/ɡ/', ms: 239, slowMs: 313, rec: true },
  'h': { from: '/h/', ipa: '/h/', ms: 210, slowMs: 272, rec: true },
  'i': { from: '/ɪ/', ipa: '/ɪ/', ms: 200, slowMs: 262, rec: true },
  'igh': { from: 'sky', ipa: '/aɪ/', ms: 229, slowMs: 389 },
  'j': { from: '/dʒ/', ipa: '/dʒ/', ms: 220, slowMs: 288, rec: true },
  'k': { from: '/k/', ipa: '/k/', ms: 170, slowMs: 219, rec: true },
  'l': { from: '/l/', ipa: '/l/', ms: 728, slowMs: 944, rec: true },
  'm': { from: '/m/', ipa: '/m/', ms: 700, slowMs: 935, rec: true },
  'n': { from: '/n/', ipa: '/n/', ms: 688, slowMs: 922, rec: true },
  'ng': { from: 'song', ipa: '/ŋ/', ms: 307, slowMs: 369 },
  'o': { from: '/ɒ/', ipa: '/ɒ/', ms: 579, slowMs: 773, rec: true },
  'oa': { from: 'coat', ipa: '/əʊ/', ms: 289, slowMs: 383 },
  'oi': { from: 'toy', ipa: '/ɔɪ/', ms: 210, slowMs: 621 },
  'oo': { from: 'zoo', ipa: '/uː/', ms: 420, slowMs: 525 },
  'or': { from: 'saw', ipa: '/ɔː/', ms: 309, slowMs: 459 },
  'ou': { from: 'mouse', ipa: '/aʊ/', ms: 259, slowMs: 621 },
  'p': { from: '/p/', ipa: '/p/', ms: 140, slowMs: 180, rec: true },
  'q': { from: '/kw/', ipa: '/kw/', ms: 698, slowMs: 934, rec: true },
  'r': { from: '/r/', ipa: '/r/', ms: 700, slowMs: 935, rec: true },
  's': { from: '/s/', ipa: '/s/', ms: 499, slowMs: 665, rec: true },
  'sh': { from: 'ship', ipa: '/ʃ/', ms: 355, slowMs: 379 },
  't': { from: '/t/', ipa: '/t/', ms: 150, slowMs: 192, rec: true },
  'th': { from: 'thin', ipa: '/θ/', ms: 307, slowMs: 355 },
  'u': { from: '/ʌ/', ipa: '/ʌ/', ms: 668, slowMs: 895, rec: true },
  'uu': { from: 'foot', ipa: '/ʊ/', ms: 420, slowMs: 525 },
  'v': { from: '/v/', ipa: '/v/', ms: 700, slowMs: 935, rec: true },
  'w': { from: '/w/', ipa: '/w/', ms: 700, slowMs: 935, rec: true },
  'wh': { from: '/w/', ipa: '/w/', ms: 700, slowMs: 935, rec: true },
  'x': { from: '/ks/', ipa: '/ks/', ms: 639, slowMs: 853, rec: true },
  'y': { from: '/j/', ipa: '/j/', ms: 700, slowMs: 935, rec: true },
  'z': { from: '/z/', ipa: '/z/', ms: 700, slowMs: 700, rec: true },
};
