/* letter-clips.js — GENERATED by tools/make-letter-audio.py. Do not edit.
   Which letter sounds ship as audio, and the word each one was cut out
   of. The clips are audio/letters/<key>.mp3, with a slower take of the
   same sound at <key>-slow.mp3 for the first, teaching reading.
   Voice: en_GB-cori-medium (Piper), trained on public-domain LibriVox recordings. */
window.LETTER_CLIPS = {
  'a': { word: 'cat', ms: 307, slowMs: 547 },
  'b': { word: 'ball', ms: 180, slowMs: 229 },
  'c': { word: 'cat', ms: 140, slowMs: 180 },
  'ch': { word: 'chip', ms: 239, slowMs: 289 },
  'ck': { word: 'kite', ms: 120, slowMs: 170 },
  'd': { word: 'dog', ms: 160, slowMs: 210 },
  'e': { word: 'egg', ms: 403, slowMs: 415 },
  'f': { word: 'fish', ms: 295, slowMs: 391 },
  'g': { word: 'goat', ms: 170, slowMs: 170 },
  'h': { word: 'hat', ms: 221, slowMs: 339 },
  'i': { word: 'pig', ms: 403, slowMs: 525 },
  'j': { word: 'jam', ms: 210, slowMs: 279 },
  'k': { word: 'kite', ms: 120, slowMs: 180 },
  'l': { word: 'lamp', ms: 323, slowMs: 459 },
  'm': { word: 'mat', ms: 299, slowMs: 383 },
  'n': { word: 'nut', ms: 325, slowMs: 467 },
  'ng': { word: 'king', ms: 299, slowMs: 383 },
  'o': { word: 'dog', ms: 307, slowMs: 415 },
  'p': { word: 'pen', ms: 110, slowMs: 140 },
  'q': { word: 'queen', ms: 160, slowMs: 229 },
  'r': { word: 'rat', ms: 349, slowMs: 459 },
  's': { word: 'sun', ms: 355, slowMs: 467 },
  'sh': { word: 'ship', ms: 355, slowMs: 495 },
  't': { word: 'tent', ms: 110, slowMs: 160 },
  'th': { word: 'thin', ms: 289, slowMs: 395 },
  'u': { word: 'cup', ms: 341, slowMs: 439 },
  'v': { word: 'van', ms: 339, slowMs: 415 },
  'w': { word: 'web', ms: 291, slowMs: 371 },
  'wh': { word: 'web', ms: 259, slowMs: 403 },
  'x': { word: 'box', ms: 359, slowMs: 459 },
  'y': { word: 'yak', ms: 239, slowMs: 299 },
  'z': { word: 'zoo', ms: 305, slowMs: 415 },
};
